[custom.all.idris2-http-server]
type = "local"
path = "."
ipkg = "idris2-http-server.ipkg"
test = "test/test.ipkg"

[custom.all.idris2-http-server-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.idris2-http-types]
type = "github"
url = "https://github.com/mtaylor91/idris2-http-types"
commit = "2b282a053552d1bb45e5bdd0eeb86145584d3d41"
ipkg = "idris2-http-types.ipkg"
